import { ArrowLeft, ArrowRight, Check, MailCheck, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Button } from "@workspace/geslaagd-momentum/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/geslaagd-momentum/components/ui/card";
import { Input } from "@workspace/geslaagd-momentum/components/ui/input";
import { Label } from "@workspace/geslaagd-momentum/components/ui/label";
import { Badge } from "@workspace/geslaagd-momentum/components/ui/badge";
import { Shell, Brand } from "./_shared/Frame";

export type AuthMode = "login" | "signup" | "verify" | "forgot" | "expired" | "reset" | "success" | "loading";
export function AuthStates({ initialMode = "login" }: { initialMode?: AuthMode }) {
  const [mode, setMode] = useState<AuthMode>(initialMode);
  if (mode === "loading") return <Shell className="grid place-items-center"><div className="text-center"><Brand /><div className="mt-12 h-2 w-48 animate-pulse rounded bg-muted" /><p className="meta mt-4 text-muted-foreground">sessie beveiligen</p></div></Shell>;
  const title = mode === "login" ? "Welkom terug." : mode === "signup" ? "Begin met overzicht." : mode === "verify" ? "Check je inbox." : mode === "forgot" ? "Kies opnieuw." : mode === "expired" ? "Deze link is verlopen." : mode === "reset" ? "Een nieuw wachtwoord." : "Je bent weer binnen.";
  return <Shell className="grid min-h-screen place-items-center grid-lines p-4"><Card className="w-full max-w-md"><CardHeader><Brand /><Badge className="mt-8 w-fit" variant="outline"><ShieldCheck size={14} /> veilige toegang</Badge><CardTitle className="display pt-2 text-3xl">{title}</CardTitle><p className="text-sm text-muted-foreground">{mode === "verify" ? "We stuurden een link naar mila@voorbeeld.nl." : mode === "expired" ? "Vraag een nieuwe link aan om verder te gaan." : "Je onderwerpen en voortgang bewaren op één plek."}</p></CardHeader><CardContent>{mode === "verify" ? <div className="space-y-4"><MailCheck className="text-primary" size={32} /><Button className="w-full" onClick={() => setMode("login")}>Stuur opnieuw <ArrowRight /></Button><Button variant="ghost" onClick={() => setMode("login")}><ArrowLeft /> Terug naar inloggen</Button></div> : mode === "expired" ? <div className="space-y-4"><Button className="w-full" onClick={() => setMode("forgot")}>Nieuwe herstel-link <ArrowRight /></Button><Button variant="ghost" onClick={() => setMode("login")}>Terug naar inloggen</Button></div> : mode === "success" ? <div className="space-y-4"><div className="flex items-center gap-2 text-primary"><Check /> Wachtwoord aangepast.</div><Button className="w-full" onClick={() => setMode("login")}>Naar inloggen</Button></div> : <form className="space-y-4" onSubmit={(e) => {e.preventDefault(); setMode(mode === "forgot" ? "verify" : mode === "signup" ? "verify" : mode === "reset" ? "success" : "login");}}><div><Label htmlFor="email">E-mailadres</Label><Input id="email" type="email" autoComplete="email" defaultValue="mila@voorbeeld.nl" /></div>{!["forgot","reset"].includes(mode) && <div><Label htmlFor="password">Wachtwoord</Label><Input id="password" type="password" autoComplete={mode === "signup" ? "new-password" : "current-password"} defaultValue="studie123" /></div>}{mode === "reset" && <div><Label htmlFor="confirm">Herhaal wachtwoord</Label><Input id="confirm" type="password" autoComplete="new-password" /></div>}<Button className="w-full" type="submit">{mode === "signup" ? "Account aanmaken" : mode === "forgot" ? "Stuur herstel-link" : mode === "reset" ? "Wachtwoord opslaan" : "Inloggen"} <ArrowRight /></Button><div className="flex flex-wrap justify-between gap-2 text-sm"><Button variant="link" type="button" onClick={() => setMode(mode === "login" ? "forgot" : "login")}>{mode === "login" ? "Wachtwoord vergeten?" : "Terug naar inloggen"}</Button><Button variant="link" type="button" onClick={() => setMode(mode === "login" ? "signup" : "login")}>{mode === "login" ? "Aanmelden" : "Inloggen"}</Button></div></form>}</CardContent></Card></Shell>;
}

export default AuthStates;