import { BookOpen, ChevronRight, GraduationCap, Menu, Search, Sparkles } from "lucide-react";
import { useState } from "react";
import { Badge } from "@workspace/geslaagd-momentum/components/ui/badge";
import { Button } from "@workspace/geslaagd-momentum/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/geslaagd-momentum/components/ui/card";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@workspace/geslaagd-momentum/components/ui/sheet";
import { Prompt, Shell, Brand } from "./_shared/Frame";

export default function DashboardMobile() {
  const [tab, setTab] = useState<"overzicht" | "catalogus">("overzicht");
  return <Shell dark><header className="flex items-center justify-between border-b border-border px-5 py-4"><Brand dark /><Badge variant="outline"><GraduationCap size={14} /> 6 VWO</Badge><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" aria-label="Menu openen"><Menu /></Button></SheetTrigger><SheetContent><SheetHeader><SheetTitle>Mijn leeromgeving</SheetTitle></SheetHeader><div className="mt-8 grid gap-2"><Button variant={tab === "overzicht" ? "secondary" : "ghost"} className="justify-start" onClick={() => setTab("overzicht")}>Overzicht</Button><Button variant="ghost" className="justify-start">Studiecoach</Button><Button variant={tab === "catalogus" ? "secondary" : "ghost"} className="justify-start" onClick={() => setTab("catalogus")}>Catalogus</Button></div></SheetContent></Sheet></header><div className="shell py-7"><p className="meta text-primary">jouw leeromgeving</p><h1 className="display mt-3 text-4xl">Waar wil je vandaag grip op krijgen?</h1><p className="mt-3 text-muted-foreground">Kies een route die je verder brengt.</p><div className="mt-6 flex gap-1 rounded-lg border border-border p-1"><Button size="sm" variant={tab === "overzicht" ? "secondary" : "ghost"} onClick={() => setTab("overzicht")}>Overzicht</Button><Button size="sm" variant={tab === "catalogus" ? "secondary" : "ghost"} onClick={() => setTab("catalogus")}>Catalogus</Button></div>{tab === "overzicht" ? <div className="mt-10 space-y-6"><Prompt /><Card><CardHeader><CardTitle className="font-serif text-xl">Verder met een onderwerp</CardTitle></CardHeader><CardContent className="space-y-2">{["De Nederlandse rechtsstaat","Cellulaire ademhaling"].map((item) => <Button variant="ghost" className="h-auto w-full justify-between py-4" key={item}><span className="flex items-center gap-3 text-left"><BookOpen className="text-primary" /><span><strong>{item}</strong><small className="block text-muted-foreground">Studiecoach · gisteren</small></span></span><ChevronRight /></Button>)}</CardContent></Card><Button className="w-full justify-start" variant="secondary"><Sparkles /> Vraag de coach</Button></div> : <div className="mt-8 space-y-3"><Button className="w-full justify-start" variant="outline"><Search /> Zoek vak, boek of hoofdstuk</Button>{["Nederlands","Wiskunde B","Geschiedenis","Biologie"].map((subject, index) => <Card key={subject}><CardContent className="flex items-center justify-between p-5"><div><span className="meta text-muted-foreground">0{index + 1} · vak</span><h2 className="mt-2 font-serif text-lg">{subject}</h2></div><ChevronRight className="text-primary" /></CardContent></Card>)}</div>}</div></Shell>;
}