import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Clock3, FileText } from "lucide-react";
import { useState } from "react";
import { Badge } from "@workspace/geslaagd-momentum/components/ui/badge";
import { Button } from "@workspace/geslaagd-momentum/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/geslaagd-momentum/components/ui/card";
import { Progress } from "@workspace/geslaagd-momentum/components/ui/progress";
import { Source, Shell, Brand } from "./_shared/Frame";

export type StudyDetailState = "ready" | "loading" | "empty" | "error";
export function StudyDetail({ initialState = "ready" }: { initialState?: StudyDetailState }) {
  const [state, setState] = useState<StudyDetailState>(initialState);
  if (state === "loading") return <Shell dark><div className="shell max-w-4xl"><Brand dark /><div className="mt-20 space-y-5 animate-pulse"><div className="h-4 w-24 rounded bg-muted" /><div className="h-12 w-3/4 rounded bg-muted" /><div className="h-40 rounded-xl bg-muted" /></div></div></Shell>;
  if (state === "empty") return <Shell dark><div className="shell max-w-3xl"><Brand dark /><Card className="mt-20"><CardContent className="p-10 text-center"><BookOpen className="mx-auto text-primary" size={34} /><h1 className="display mt-5 text-3xl">Je studieplek staat klaar.</h1><p className="mx-auto mt-3 max-w-md text-muted-foreground">Er is nog geen samenvatting gemaakt. Vraag de coach om de eerste kern.</p><Button className="mt-6" onClick={() => setState("ready")}>Maak een start <ArrowRight /></Button></CardContent></Card></div></Shell>;
  if (state === "error") return <Shell dark><div className="shell max-w-3xl"><Brand dark /><Card className="mt-20 border-destructive/50"><CardContent className="p-10"><h1 className="display text-3xl">Deze studieplek laadt niet.</h1><p className="mt-3 text-muted-foreground">We konden je bronnen niet ophalen.</p><Button className="mt-6" onClick={() => setState("ready")}>Opnieuw proberen</Button></CardContent></Card></div></Shell>;
  return <Shell dark><header className="border-b border-border"><div className="shell flex justify-between py-4"><Brand dark /><Button variant="ghost" size="sm" onClick={() => setState("loading")}><Clock3 /> Loading preview</Button></div></header><div className="shell max-w-5xl"><Button variant="ghost" className="mb-8 px-0" onClick={() => setState("empty")}><ArrowLeft /> Mijn leeromgeving</Button><div className="flex flex-wrap items-start justify-between gap-6"><div><Badge variant="outline">studiecoach · geschiedenis</Badge><h1 className="display mt-4 text-4xl md:text-6xl">De Nederlandse rechtsstaat</h1><p className="mt-4 max-w-2xl text-lg text-muted-foreground">Je begrijpt hoe grondrechten, machtenscheiding en de democratische rechtsstaat samenhangen.</p></div><div className="min-w-52 rounded-xl border border-border p-4"><p className="meta text-muted-foreground">voortgang</p><p className="mt-2 font-serif text-2xl">3 van 5</p><Progress className="mt-3" value={60} /></div></div><div className="mt-12 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><div className="flex items-center gap-2"><CheckCircle2 className="text-primary" size={18} /><CardTitle className="font-serif text-2xl">De kern</CardTitle></div></CardHeader><CardContent className="space-y-5 leading-relaxed text-muted-foreground"><p><strong className="text-foreground">Een rechtsstaat beschermt burgers tegen willekeur.</strong> De overheid is gebonden aan regels en grondrechten. Onafhankelijke rechters bewaken die grens.</p><p>In Nederland is de macht verdeeld over wetgevende, uitvoerende en rechterlijke macht. Die verdeling voorkomt dat één partij alle beslissingen bepaalt.</p><Button onClick={() => setState("ready")}>Volgende stap: oefen <ArrowRight /></Button></CardContent></Card><Card><CardHeader><CardTitle className="font-serif text-xl">Bronnen bij deze kern</CardTitle></CardHeader><CardContent><Source name="Rijksoverheid · De Grondwet" detail="rijksoverheid.nl · gecontroleerd" /><Source name="ProDemos · Rechtsstaat" detail="prodemos.nl · uitleg" /><div className="mt-4 flex items-center gap-2 text-sm text-chart-2"><FileText size={16} /> 2 bronnen passen bij je vraag</div></CardContent></Card></div></div></Shell>;
}

export default StudyDetail;